TahoeMultiTenancyBundle_invitation:
    resource: @TahoeMultiTenancyBundle/Resources/config/routing/invitation.yml
    prefix: /crud/invitation

TahoeMultiTenancyBundle_tenantuser:
    resource: @TahoeMultiTenancyBundle/Resources/config/routing/tenantuser.yml
    prefix: /crud/tenant-users

TahoeMultiTenancyBundle_tenant:
    resource: @TahoeMultiTenancyBundle/Resources/config/routing/tenant.yml
    prefix: /

TahoeMultiTenancyBundle_subscription:
    resource: @TahoeMultiTenancyBundle/Resources/config/routing/subscription.yml
    prefix: /

start_index:
    path: /
    defaults: {_controller: TahoeMultiTenancyBundle:Start:index}

pending_invitation:
    path:  /pending/invitations
    defaults: {_controller: 'TahoeMultiTenancyBundle:Invitation:pending'}

invitation_action:
    path: /invitation/action
    defaults: {_controller: 'TahoeMultiTenancyBundle:Invitation:action' }
    requirements:
        _method: post
        id: \d+
